apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-02-22T16:14:47Z"
  labels:
    fruit: banana
  name: banana-boat
  namespace: pineapple
  resourceVersion: "7753"
  uid: b560f07d-df98-4520-a169-3632c8423979
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: banana-boat-cont
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-nssxf
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: worker2
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-nssxf
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-02-22T16:14:47Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-02-22T16:15:08Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-02-22T16:15:08Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-02-22T16:14:47Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://3415a6f999cccb61a1790ad1b6622fc7be5bdf203d3591e8837ac46ba4b846a7
    image: docker.io/library/nginx:latest
    imageID: docker.io/library/nginx@sha256:91734281c0ebfc6f1aea979cffeed5079cfe786228a71cc6f1f46a228cde6e34
    lastState: {}
    name: banana-boat-cont
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-02-22T16:15:07Z"
  hostIP: 192.168.100.8
  phase: Running
  podIP: 10.44.0.1
  podIPs:
  - ip: 10.44.0.1
  qosClass: BestEffort
  startTime: "2025-02-22T16:14:47Z"
