apiVersion: v1
kind: Service
metadata:
  name: lemonservice
  namespace: coconut
  labels:
    fruit: lemon
spec:
  selector:
    fruit: lemon
  type: NodePort
  ports:
  - port: 80
    targetPort:  80
